from django.urls import path
from .views import (
    HomeView,
    AgenteListView,
    AgenteDetailView,
    AgenteCreateView,
    AgenteUpdateView,
    AgenteDeleteView,
    ClienteListView,
    ClienteDetailView,
    ClienteCreateView,
    ClienteUpdateView,
    ClienteDeleteView,
    LlamadaListView,
    LlamadaDetailView,
    LlamadaCreateView,
    LlamadaUpdateView,
    LlamadaDeleteView,
    ProblemaReportadoListView,
    ProblemaReportadoDetailView,
    ProblemaReportadoCreateView,
    ProblemaReportadoUpdateView,
    ProblemaReportadoDeleteView,
    EncuestaSatisfaccionListView,
    EncuestaSatisfaccionDetailView,
    EncuestaSatisfaccionCreateView,
    EncuestaSatisfaccionUpdateView,
    EncuestaSatisfaccionDeleteView,
    CampanaListView,
    CampanaDetailView,
    CampanaCreateView,
    CampanaUpdateView,
    CampanaDeleteView,
    ParticipacionCampanaListView,
    ParticipacionCampanaDetailView,
    ParticipacionCampanaCreateView,
    ParticipacionCampanaUpdateView,
    ParticipacionCampanaDeleteView,
)

app_name = "app_callcenter"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("agentes/", AgenteListView.as_view(), name="agente-list"),
    path("agentes/<int:pk>/", AgenteDetailView.as_view(), name="agente-detail"),
    path("agentes/crear/", AgenteCreateView.as_view(), name="agente-create"),
    path("agentes/<int:pk>/actualizar/", AgenteUpdateView.as_view(), name="agente-update"),
    path(
        "agentes/<int:pk>/eliminar/",
        AgenteDeleteView.as_view(),
        name="agente-delete",
    ),
    path("clientes/", ClienteListView.as_view(), name="cliente-list"),
    path("clientes/<int:pk>/", ClienteDetailView.as_view(), name="cliente-detail"),
    path("clientes/crear/", ClienteCreateView.as_view(), name="cliente-create"),
    path("clientes/<int:pk>/actualizar/", ClienteUpdateView.as_view(), name="cliente-update"),
    path("clientes/<int:pk>/eliminar/", ClienteDeleteView.as_view(), name="cliente-delete"),
    path("llamadas/", LlamadaListView.as_view(), name="llamada-list"),
    path("llamadas/<int:pk>/", LlamadaDetailView.as_view(), name="llamada-detail"),
    path("llamadas/crear/", LlamadaCreateView.as_view(), name="llamada-create"),
    path("llamadas/<int:pk>/actualizar/", LlamadaUpdateView.as_view(), name="llamada-update"),
    path("llamadas/<int:pk>/eliminar/", LlamadaDeleteView.as_view(), name="llamada-delete"),
    path("problemas/", ProblemaReportadoListView.as_view(), name="problema-list"),
    path("problemas/<int:pk>/", ProblemaReportadoDetailView.as_view(), name="problema-detail"),
    path("problemas/crear/", ProblemaReportadoCreateView.as_view(), name="problema-create"),
    path("problemas/<int:pk>/actualizar/", ProblemaReportadoUpdateView.as_view(), name="problema-update"),
    path("problemas/<int:pk>/eliminar/", ProblemaReportadoDeleteView.as_view(), name="problema-delete"),
    path("encuestas/", EncuestaSatisfaccionListView.as_view(), name="encuesta-list"),
    path("encuestas/<int:pk>/", EncuestaSatisfaccionDetailView.as_view(), name="encuesta-detail"),
    path("encuestas/crear/", EncuestaSatisfaccionCreateView.as_view(), name="encuesta-create"),
    path("encuestas/<int:pk>/actualizar/", EncuestaSatisfaccionUpdateView.as_view(), name="encuesta-update"),
    path("encuestas/<int:pk>/eliminar/", EncuestaSatisfaccionDeleteView.as_view(), name="encuesta-delete"),
    path("campanas/", CampanaListView.as_view(), name="campana-list"),
    path("campanas/<int:pk>/", CampanaDetailView.as_view(), name="campana-detail"),
    path("campanas/crear/", CampanaCreateView.as_view(), name="campana-create"),
    path("campanas/<int:pk>/actualizar/", CampanaUpdateView.as_view(), name="campana-update"),
    path("campanas/<int:pk>/eliminar/", CampanaDeleteView.as_view(), name="campana-delete"),
    path("participaciones/", ParticipacionCampanaListView.as_view(), name="participacion-list"),
    path("participaciones/<int:pk>/", ParticipacionCampanaDetailView.as_view(), name="participacion-detail"),
    path("participaciones/crear/", ParticipacionCampanaCreateView.as_view(), name="participacion-create"),
    path("participaciones/<int:pk>/actualizar/", ParticipacionCampanaUpdateView.as_view(), name="participacion-update"),
    path("participaciones/<int:pk>/eliminar/", ParticipacionCampanaDeleteView.as_view(), name="participacion-delete"),
]
