# Generated by Django 5.0.13 on 2025-11-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteCallCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
                ('habilidades_idiomas', models.TextField(blank=True, null=True)),
                ('estado_agente', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campana', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo_campana', models.CharField(blank=True, max_length=50, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('publico_objetivo', models.TextField(blank=True, null=True)),
                ('presupuesto_campana', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteCallCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('historial_problemas', models.TextField(blank=True, null=True)),
                ('nivel_satisfaccion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, null=True)),
                ('tipo_llamada', models.CharField(blank=True, max_length=50, null=True)),
                ('resultado_llamada', models.CharField(blank=True, max_length=50, null=True)),
                ('grabacion_url', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_llamada', models.TextField(blank=True, null=True)),
                ('calificacion_cliente', models.IntegerField(blank=True, null=True)),
                ('id_agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_callcenter.agentecallcenter')),
                ('id_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_callcenter.clientecallcenter')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaSatisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encuesta', models.DateTimeField(blank=True, null=True)),
                ('calificacion_general', models.IntegerField(blank=True, null=True)),
                ('calificacion_agente', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_envio_encuesta', models.DateTimeField(blank=True, null=True)),
                ('fue_completada', models.BooleanField(blank=True, null=True)),
                ('id_llamada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_callcenter.llamada')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_participacion', models.DateField(blank=True, null=True)),
                ('fecha_fin_participacion', models.DateField(blank=True, null=True)),
                ('num_llamadas_realizadas', models.IntegerField(blank=True, null=True)),
                ('num_exitos', models.IntegerField(blank=True, null=True)),
                ('tiempo_promedio_llamada', models.IntegerField(blank=True, null=True)),
                ('id_agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_callcenter.agentecallcenter')),
                ('id_campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_callcenter.campana')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaReportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_problema', models.TextField(blank=True, null=True)),
                ('estado_problema', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_resolucion_estimada', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_problema', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios_resolucion', models.TextField(blank=True, null=True)),
                ('id_agente_resolvio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_callcenter.agentecallcenter')),
                ('id_llamada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_callcenter.llamada')),
            ],
        ),
    ]
