# Generated by Django 5.0.13 on 2025-12-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_callcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentecallcenter',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_agentes/'),
        ),
        migrations.AddField(
            model_name='clientecallcenter',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes/'),
        ),
    ]
