# Generated by Django 5.0.13 on 2025-12-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_callcenter', '0002_agentecallcenter_foto_clientecallcenter_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientecallcenter',
            name='foto',
        ),
    ]
