# Generated by Django 5.0.13 on 2025-12-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_callcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentecallcenter',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='agentes/'),
        ),
        migrations.AddField(
            model_name='clientecallcenter',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='estado_agente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='fecha_contratacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='habilidades_idiomas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='agentecallcenter',
            name='turno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='campana',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campana',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campana',
            name='nombre_campana',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campana',
            name='objetivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clientecallcenter',
            name='contacto_principal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientecallcenter',
            name='email_contacto',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientecallcenter',
            name='fecha_registro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientecallcenter',
            name='nivel_satisfaccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientecallcenter',
            name='nombre_empresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientecallcenter',
            name='sector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientecallcenter',
            name='telefono_contacto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='calificacion_general',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='fecha_encuesta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='fue_completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='encuestasatisfaccion',
            name='id_llamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_callcenter.llamada'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='fecha_hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='grabacion_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='id_agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_callcenter.agentecallcenter'),
        ),
        migrations.AlterField(
            model_name='llamada',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_callcenter.clientecallcenter'),
        ),
        migrations.AlterField(
            model_name='participacioncampana',
            name='fecha_inicio_participacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='participacioncampana',
            name='id_agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_callcenter.agentecallcenter'),
        ),
        migrations.AlterField(
            model_name='participacioncampana',
            name='id_campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_callcenter.campana'),
        ),
        migrations.AlterField(
            model_name='participacioncampana',
            name='num_exitos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participacioncampana',
            name='num_llamadas_realizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participacioncampana',
            name='tiempo_promedio_llamada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problemareportado',
            name='descripcion_problema',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problemareportado',
            name='estado_problema',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='problemareportado',
            name='id_agente_resolvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_callcenter.agentecallcenter'),
        ),
        migrations.AlterField(
            model_name='problemareportado',
            name='id_llamada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_callcenter.llamada'),
        ),
        migrations.AlterField(
            model_name='problemareportado',
            name='prioridad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='problemareportado',
            name='tipo_problema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
